### ISSUE TITLE
Receiving the wrong object from API when getting item by codename.

### ISSUE THREAD

**Issue by LewisParkinson** [Kentico/kontent-boilerplate-net#101]
### Description
I have two objects '**Object1**' and '**Object2**'. '**Object2**' is a child of '**Object1**' (according to the CMS structure) and I have created a custom method that gets the correct URL path of the current page by it's codename  - i.e. "/{object1Url}/{currentPageUrl}" or "/{object1Url}/{object2Url}/{currentPageUrl}".

I first check to see if the current page is of type '**Object1**' by using the following request:

`IDeliveryItemResponse<Object1> object1Response = _deliveryClient.GetItemAsync<Object1>(codename,
                                                                                        new EqualsFilter("system.type", Object1.Codename),
                                                                                        new ElementsParameter(Object1.Field1Codename,
                                                                                                              Object1.Field2Codename)).Result;`

If this object is null, I know that the current page is a child of '**Object1**'. So, I then check for '**Object2**' by the codename, using the following:

`IDeliveryItemResponse<Object2> object2Response = _deliveryClient.GetItemAsync<Object2>(codename,
                                                                                        new EqualsFilter("system.type", Object2.Codename),
                                                                                        new ElementsParameter(Object2.Field1Codename,
                                                                                                              Object2.Field2Codename)).Result;`

I am then calling this custom method in two separate places and get two different results for the same codename (Content Item). In one of the place I am getting the correct result. But, in the second place, I am getting the Content Item of type '**Object2**' returned in the '**object1Response**' object, where I check to see if it is of type '**Object1**'. So, the URL I build is incorrect for the type of page it is.

This only seems to happen when the current page is a child of the '**Object2**' section - i.e. "/{object1Url}/{object2Url}/{currentPageUrl}". The codename I'm passing into the method is definitely for a Content Item of type '**Object2**' - I have check this a couple time and also had a colleague double check.

Has anyone come across this as well and have any ways around it?

**Comment by Simply007** [comment]
Hello @LewisParkinson,

thanks for bringing this up, but this issue might fit better into the [.NET Delivery SDK repository](https://github.com/Kentico/kontent-delivery-sdk-net).

I have read through the issue and the first thing you could do is to check the response object, get the URL of the request and then try to send the plain GET HTTP request. Then check the Typeprovider, if the mapping of a type to model classes is correct and if the TypeResolver is correctly initialized (find DI, or directly).

---

The second and I think the more viable option would be to use [Runtime typing](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Runtime-Typing#how-to-use-runtime-typing), so use `object` as the expected result and then decide by the item actual type.


```csharp
var response = await client.GetItemAsync<object>(codename);

// response.Item would be strongly typed
var type = typeof(response.Item);
```

**Comment by LewisParkinson** [comment]
Hi @Simply007,

Thanks for you response.

I have tried both method you have suggested and still get the same result as described above. I have also tried using the `_deliveryClient.GetItemsAsync<Object1>()` request to see how many items are being returned. I only get the 1 item with the codename sent through to the method. It's assigning it to the 'Object1' object every time, when in some cases it should be the 'Object2' object.

I have noticed that, within the code I provided in the description, the URL request used is different in both places I'm calling the method. One is adding the "system.type" filter and the other isn't. This is why I'm getting two different results. I'm just a bit confused seeing as this is a single custom method, which is called in two separate places of the project. But, the URL request is different for each place it's used. All I'm sending to the 
method is a codename to search by. Other than that the request is exactly the same in both cases.

The method I have created in full (as it is now) - in one case the 'primary.Items?.Count() > 0' check is always true, which should be the case:

`public async Task<string> GetPath(string taxonomyCodename)
        {
            string path = string.Empty;

            if (area != string.Empty)
            {
                IDeliveryItemListingResponse<Object1> primary = await _deliveryClient.GetItemsAsync<Object1>(
                                                                                        new AllFilter($"elements.{Object1.TaxonomyFieldCodename}", taxonomyCodename),
                                                                                        new ElementsParameter(Object1.TitleCodename,
                                                                                                              Object1.UrlCodename));

                // If primary does not return anything, then we must be in a secondary object.
                if (primary.Items?.Count() > 0)
                {
                    path = $"/area/primary.Items.FirstOrDefault().Url}";
                }
                else
                {
                    IDeliveryItemListingResponse<Object2> secondary = await _deliveryClient.GetItemsAsync<Object2>(
                                                                                new AllFilter($"elements.{Object2.TaxonomyFieldCodename}", taxonomyCodename),
                                                                                new ElementsParameter(Object2.TitleCodename,
                                                                                                      Object2.ParentObjectCodename,
                                                                                                      Object2.UrlCodename),
                                                                                new DepthParameter(2));

                    if (secondary.Items?.Count() > 0)
                    {
                        Object2 object2 = secondary.Items.FirstOrDefault();
                        Object1 object1 = object2 .ParentObject.Select(prt => (Object1)prt).FirstOrDefault();

                        path = $"/area/{object1.Url}/{object2.Url}";
                    }
                }
            }

            return path;
        }`

I call this method from **CustomContentLinkUrlResolver.cs** and also from my **SeoController.cs** to get the correct path for the Sitemap.xml. When calling the above method within **CustomContentLinkUrlResolver.cs** is where I'm getting the issue.

**Comment by Simply007** [comment]
Could you share the code of the `TypeProvider` you are using to initialize the `_deliveryClient`? 

And could you double-check that the types in registration are correctly set with the ones in the Kontent app? 

If the URL does not contain the `type` filter, it might be the root cause -> Type Provider was no able to deduct the type codename base on the type provided in generics.

**Comment by LewisParkinson** [comment]
@Simply007,

Here is the type provider I'm using:

`public class CustomTypeProvider : ITypeProvider
    {
        private static readonly Dictionary<Type, string> _codenames = new Dictionary<Type, string>
        {
            {typeof(Article), "article"},
            {typeof(GenericContent), "generic_content"},
            {typeof(Home), "home"},
            {typeof(Object1), "object_1"},
            {typeof(Object2), "object_2"}
        };

        public Type GetType(string contentType)
        {
            return _codenames.Keys.FirstOrDefault(type => GetCodename(type).Equals(contentType));
        }

        public string GetCodename(Type contentType)
        {
            return _codenames.TryGetValue(contentType, out var codename) ? codename : null;
        }
    }`

These types are correctly set up to match what is in the Kontent App.

**Comment by Simply007** [comment]
That's a tough one! 
I don't see any obvious issue and I have double-checked the code you provided and also tried to simulate your situation locally and everything seems to work.

I have also created a test that is using a custom link resolver and inside it is using the same instance of the client to load the related data using the [dynamic typing feature I mentioned above](https://github.com/Kentico/kontent-boilerplate-net/issues/101#issuecomment-831781438) and everything seems to work. I have also tried to load Item with `system.type` element filter as you have [in the issue description](https://github.com/Kentico/kontent-boilerplate-net/issues/101#issue-871020085) and the result was the same.

Test: https://github.com/Kentico/kontent-delivery-sdk-net/blob/22ff7021bc6a9307d2ca76953f901e3cbd318641/Kentico.Kontent.Delivery.Tests/ContentLinkResolverTests.cs#L154-L223

Test result: https://github.com/Kentico/kontent-delivery-sdk-net/runs/2517609768

---

I can see two options here. 

The first one would be to use [SoureLink on your side](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Using-Source-Link-for-debugging) and debug the data fetching on your project using the symbols from the symbol server to find the root cause. I would recommend focusing on [DeliveryClient](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.Delivery/DeliveryClient.cs) [DeliveryEndpointUrlBuilder](https://github.com/Kentico/kontent-delivery-sdk-net/blob/master/Kentico.Kontent.ImageTransformation/Delivery/DeliveryEndpointUrlBuilder.cs) and [ModelProvider.GetContentItemModelAsync](https://github.com/Kentico/kontent-delivery-sdk-net/blob/ffbfaa604f3262937c13d8440f16471e1717d7cc/Kentico.Kontent.Delivery/ContentItems/ModelProvider.cs#L79).

The second option would be providing me with a replicable environment (a simple console app connected to Kontent project would do the job) and I can test it out and identify the root cause of the issue (basically by doing the first option on my side).

**Comment by LewisParkinson** [comment]
Thanks for your help. Everything I am requesting looks fine. The content type code name is correct and the fields codename I'm search within that content type, is correct. It's just the data being returned isn't content type I requested.

I have amended my code and created a new method, just for the **CustomContentLinkUrlResolver**, that gets the content item by it's codename. But, still getting the same issue.

Just a quick questions about the following code:

`IDeliveryItemListingResponse<Object2> secondaryTheme = await _deliveryClient.GetItemsAsync<Object2>(
                                                                                        new EqualsFilter("system.type", "object_2"),
                                                                                        new EqualsFilter("system.codename", "test"),
                                                                                        new DepthParameter(2));`

Shouldn't it search for a content item of the **"object_2"** type and has the codename of **"test"**?

Because, what I am expecting in the above code I'm getting in the following when there isn't a content item of type **"object_1"** with the codename **"test"**:

`IDeliveryItemListingResponse<Object1> primaryTheme = await _deliveryClient.GetItemsAsync<Object1>(
                                                                                        new EqualsFilter("system.type", "object_1"),
                                                                                        new EqualsFilter("system.codename", "test"));`

Or does it just try and find the content item with the codename **"test"** and assign it to the **"object_1"** content type? This might be what is causing the issue, as **Object1** and **Object2** are pretty much the same class. **Object2** just contains a few extra properties.

**Comment by Simply007** [comment]
If you run this code 

```csharp
IDeliveryItemListingResponse<Object2> secondaryTheme = await _deliveryClient.GetItemsAsync<Object2>( new EqualsFilter("system.type", "object_2"), new EqualsFilter("system.codename", "test"), new DepthParameter(2));
```

SDK will basically send a request to:

```plain
https://deliver.kontent.ai/<PROJECTID>/items?system.type=object_2&system.codename=test&depth=2
```

Then get the returning data and try to map the content to the `Object2` model.

**Comment by LewisParkinson** [comment]
Ok, thank you for your help. The issue is because the objects are too similar.

**Comment by Simply007** [comment]
> Surely, when I filter by `system.type` I should only receive that content type back though? for the following line of code I'm receiving data for `Object2` when I'm filtering by `Object1`:
> 
> `IDeliveryItemListingResponse<Object1> secondaryTheme = await _deliveryClient.GetItemsAsync<Object1>( new EqualsFilter("system.type", "object_1"), new EqualsFilter("system.codename", "test"), new DepthParameter(2));`

You should get the items based on  "object_1" item.

Could you share the URL (`ApiResponse.RequestUrl` property) from `secondaryTheme` object?

**Comment by Simply007** [comment]
Hi!

This issue has gone quiet. 👻
It’s been a while since the last update here.

If we missed anything on this issue or if you want to keep it open, please reply here. 

Thanks for being a part of the Kentico community!

**Comment by LewisParkinson** [comment]
Hi,

Sorry, I forgot to reply. 

The issue was to do with the two objects being too similar, which meant that content for Object2 could be assigned to Object 1. The thing I still can't figure out is why the codename of the content type I request wasn't in the request. But, I have found a work around that involves using the selected Taxonomy term to determine where the item sits instead.

Thanks for all your help.
