### ISSUE TITLE
Publish the cache and delivery code as a NuGet package

### ISSUE THREAD

**Issue by mcetkovsky** [Kentico/kontent-boilerplate-net#60]
The current boilerplate project is used to start a new web site on Kentico (users are instructed to do so). As such, users get the than-current code at the time of creating a new web site project. All fixes and improvements you made after that moment are usually missed and they never reach production for already existing web sites.

The boilerplate project contains two parts with different usage scenarios:

- Code encapsulating the official Kentico library and providing additional library-like features (caching, cache reset webhook, signature check etc.). This part tends to be kept intact in the result web site project.
- Sample website which shows how to get and show data retrieved from Kentico. This part tends to be heavily replaced in the result web site project.

I would like to see the encapsulating code to be published as a somehow-officially-supported NuGet package.

It will have several benefits:

- It makes sense. Currently, the boilerplate code mixes two different things with two different usage scenarios (encapsulating library vs. example).
- Users will get the fixes you make even for existing web site projects.
- Users will save time not being needed to manually transfer the changes you made in the meantime into their copy of the same code.

It will also have few expectations:

- Users will expect that you will maintain the library part of the code, upgrade it to support new .NET versions in a timely manner (I mean somewhere between RC and RTM) etc.

I did the split for my private projects as it makes no sense to maintain the same library code in several projects so it is feasible.

**Comment by petrsvihlik** [comment]
@JanLenoch could you please go through the notes with @mcetkovsky, express your opinion, and groom this request?

**Comment by JanLenoch** [comment]
Sure!

**Comment by mcetkovsky** [comment]
Hi @JanLenoch,

1. I do not see it as a good idea to learn or expect it to learn `dotnet new` to update an existing project. As per my opinion, it is fairly out of the scope of the command (creating a new project). On top of that, it would basically duplicate NuGet, but with some tricky and not in an algorithmically solvable cases (as the project's source code might be heavily modified - the project code is mutable while NuGet packages are treated as non-mutable).

2. As such, I vote for the NuGet way as I feel this is the right tool for the to-be-identified parts of the boilerplate code.

3. The boilerplate code has the following parts. I am going to skip repeating "in my opinion" in the options:
a) Sample web page - this should be kept as a boiler plate.
b) Memory caching with a webhook to clear the cache - a library, with an option to opt-out from the WebHook. The Options class containing settings relevant to the memory caching should be defined inside this library.
c) A class for validating Kentico Cloud's signature - a library.
d) Some random helpers, for example, support for images of different sizes etc. - a library.

4. I do not know whether all of the library parts should fit inside a single library or whether they should be several libraries. The only thing I am going to highlight as important is the ability to switch the cache clearing webhook on or off.

**Comment by petrsvihlik** [comment]
caching extracted to: https://github.com/Kentico/kontent-delivery-sdk-net/tree/master/Kentico.Kontent.Delivery.Caching

https://www.nuget.org/packages/Kentico.Kontent.Delivery.Caching/13.0.1-beta9

we'll continue with html helpers & signature validation

thanks for the idea @mcetkovsky !

**Comment by petrsvihlik** [comment]
to be continued in:
- https://github.com/Kentico/kontent-sample-app-net/issues/110
- https://github.com/Kentico/kontent-boilerplate-net/issues/93
