### ISSUE TITLE
Spike: Pick the best generic cache library

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-boilerplate-net#65]
### Expected outcome

As it makes sense to support distributed caching along with the existing support of in-memory caching, we'd like to select the most suitable 3rd party caching library to do the job.

Ideally, the library should:

* be able to handle both distributed and in-mem caching
* support strongly-typed cache entries
* be able to set dependencies among cache entries
* allow the developer to set cache eviction rules (policies) in case of memory pressure

### Reference

* https://github.com/MichaCo/CacheManager
* https://github.com/aspnet/Caching
* https://github.com/FoundatioFx/Foundatio#caching
* https://github.com/StackExchange/StackExchange.Redis

**Note:** Rewritten from #52 .

**Comment by xantari** [comment]
We currently need help with this. We are attempting to make DistributedCacheManager.cs that just uses the IDistributedCache interface microsoft provides. If you build it according to that interface it should be available for any distributed cache provider right?

**Comment by petrsvihlik** [comment]
It's my understanding that you'll be able to use any package that implements the `IDistributedCache ` interface. According to [MS docs](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed?view=aspnetcore-3.1#prerequisites), the interface is implemented by at least three caching libraries: `Microsoft.Extensions.Caching.SqlServer`, `Microsoft.Extensions.Caching.StackExchangeRedis`, and `NCache.Microsoft.Extensions.Caching.OpenSource`.

Once we finish the refactoring of the Delivery SDK, this is a good candidate for the next improvement in the .NET space. I'm taking note and will be informing you of any further progress via the other issue you submitted (#90). I can't promise when we'll be able to address it (probably Q2/2020) so in case you decide to work on it, please consider contributing back to this repository.
Thanks!

**Comment by petrsvihlik** [comment]
we'll go with `IDistributedCache`

to be continued in: https://github.com/Kentico/kontent-delivery-sdk-net/issues/196
