### ISSUE TITLE
Boilerplate support for .NET Core 3.0

### ISSUE THREAD

**Issue by ewomack2000** [Kentico/kontent-boilerplate-net#79]
The current Kentico Kontent .NET Core boilerplate only supports .NET Core 2.1. Some of our systems may have limitations for versions of .NET Core under version 3.0 (.NET Core 3.0 added some connectivity functionality for a legacy database system that we use), so an upgrade to .NET Core 3.0 would make using Kentico Kontent simpler in our case. Plus it would keep it in line with our current development plans to implement .NET Core 3.0.

**Comment by petrsvihlik** [comment]
hi @ewomack2000 ...yes. we'll be porting our samples to netcore3 and making libraries compatible with it soon.

**Comment by petrsvihlik** [comment]
Released: https://github.com/Kentico/kontent-boilerplate-net/releases/tag/4.0.0
