### ISSUE TITLE
SignatureActionFilter throwing "System.NotSupportedException"

### ISSUE THREAD

**Issue by ewomack2000** [Kentico/kontent-boilerplate-net#84]
### Brief bug description
With an ngrok url setup and the webhook url set to "webhooks/webhooks/index," I put a breakpoint on the Webhooks controller to follow the code - when it arrives at the "request.Body.Position=0" at line 26, it throws a "System.NotSupportedException" - the alternate Seek() method threw the same exception. When I commented out line 26, the system told me to change ReadToEnd() to async methods, but I ran into the same issues there. Kentico support suggested I open an issue for this.

What went wrong?
Webhook crashes on receiving a new message

### Repro steps
Step through code in SignatureActionFilter, starting with line 26

 - Platform/OS: .NET Core 3.0, Windows
 - Browser Chrome and Firefox

Add links to screenshots, if possible.
![Error](https://user-images.githubusercontent.com/13091910/69176580-999c0800-0acb-11ea-9210-43285b5c5410.png)

**Comment by petrsvihlik** [comment]
@sutrkiller could you please take a look?

**Comment by petrsvihlik** [comment]
fixed in https://github.com/Kentico/kontent-boilerplate-net/releases/tag/4.0.1
