### ISSUE TITLE
Live site not updated after new item's version is published

### ISSUE THREAD

**Issue by matus666** [Kentico/kontent-boilerplate-net#91]
### Brief bug description

Publishing a new version of an item and a corresponding webhook is being received with status code 200. This however leaves the live site still showing the old version of that item. 
It seems to be a cache issue as it doesn't get updated with the webhook.

### Expected behavior

The cache would get updated and the live site would show the new version of the item. 

### Test environment

 - Platform/OS: [e.g. .NET Core 2.1, iOS]

### Screenshots

Add links to screenshots, if possible.

**Comment by petrsvihlik** [comment]
@matus666 please provide exact steps to reproduce the issue & test environment details. otherwise, we are unable to help with this issue.
