### ISSUE TITLE
AbstractResponse.HasStaleContent is always false

### ISSUE THREAD

**Issue by LewisParkinson** [Kentico/kontent-boilerplate-net#94]
Trying to get the caching to work so that when an item is _Published_ or _Unpublished_, the cache is cleared straight away on the Live site.

I have noticed within the **InvalidatingCacheManager.cs** object, there is an if condition checking if the _value_ object is an **AbstractResponse** object and that the _value_ has the '**HasStaleContent**' property set to true (line 54 - attached screenshot below). But, when debugging this functionality, the '**HasStaleContent**' value is also returning false.

I was expected this value to be true when an item has been Published or Unpublished.

### Screenshots

![image](https://user-images.githubusercontent.com/56387747/76973539-feeff080-6927-11ea-987b-8f8898432e77.png)

**Comment by petrsvihlik** [comment]
Hi @LewisParkinson ,
the value of `HasStaleContent` will be `true` only for a short period of time. 
To be more specific, when you change a content item, Kontent will send a purge request to the CDN, which will mark the relevant records as `Stale` (`HasStaleContent` will now be returning `true` based on the `X-Stale-Content` [header](https://docs.kontent.ai/tutorials/develop-apps/get-content/best-practices-for-getting-content-in-your-app#a-cache-what-you-get) returned by the API/CDN).
At the same time, the CDN queues a request for fresh data from Kontent. Once the data is received, the `HasStaleContent` property goes back to `false`. Although we don't guarantee any specific times, this all should take less than a minute (usually it takes about 10-20 seconds).

In other words, the `HasStaleContent` property is not based on whether the content item has a new unpublished version. It's based on the state of the data in the CDN.

If you want to work with unpublished data, use the [Preview API](https://docs.kontent.ai/tutorials/write-and-collaborate/preview-content/previewing-unpublished-content).

If you want to invalidate cache by webhooks, we've just extracted caching to a separate [library](https://www.nuget.org/packages/Kentico.Kontent.Delivery.Caching) and the usage is described [here](https://github.com/Kentico/kontent-delivery-sdk-net#using-the-deliveryclient) and [here](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Instantiating-DeliveryClient-with-Configuration-API-and-DI-in-ASP.NET-Core-MVC-apps#caching). You can use the package in combination with an approach outlined in the [WebhooksController](https://github.com/Kentico/kontent-boilerplate-net/blob/master/src/content/Kentico.Kontent.Boilerplate/Areas/WebHooks/Controllers/WebhooksController.cs). We are currently in the process of updating documentation and releasing a new stable version of the Delivery SDK. It should be all in RTM in a week.

Please let me know if you have any more questions.
