### ISSUE TITLE
LinkedItems returned as null.

### ISSUE THREAD

**Issue by LewisParkinson** [Kentico/kontent-boilerplate-net#98]
I have recently upgraded a site to the latest version on this boilerplate. After the initial build of the site I noticed that most of the pages are missing sections. This is because the response from the API calls, return any linked item objects as null. When debugging I can see that the correct values are in the JSON response.

I am using the following to get the Project Individual Article: 
![image](https://user-images.githubusercontent.com/56387747/82065901-98d4df00-96c6-11ea-9014-f5c7ad803f61.png)

The following is what is returned for the ContentModules object (The correct amount of items but all null). This should be a collection of type object as different content types can be used in this section:
![image](https://user-images.githubusercontent.com/56387747/82066268-13056380-96c7-11ea-86a7-3712878fa23c.png)

This functionality was working fine before I upgraded tho the latest version on the boilerplate but can't see why this wouldn't work now. Has there been any changes been made that would stop this from working, that I have missed?

Any help would be much appreciated.

**Comment by petrsvihlik** [comment]
please make sure you register the CustomTypeProvider like this:

`services.AddSingleton<ITypeProvider, CustomTypeProvider>();`

https://github.com/Kentico/kontent-boilerplate-net/blob/master/src/content/Kentico.Kontent.Boilerplate/Startup.cs#L36

there was a [glitch](https://github.com/Kentico/kontent-boilerplate-net/commit/d8803f638bb8a80f2bf0c2c5fbd425fac20d3739#diff-9650d1e07311ba1ce599db13cdd1e25cR36) recently that has been fixed and released: https://github.com/Kentico/kontent-boilerplate-net/releases/tag/6.0.0-beta1

can you please give it a try?

**Comment by LewisParkinson** [comment]
Thanks, @petrsvihlik. This worked.
